### ISSUE TITLE
RRC detection performance much lower than the F1 score given in the paper

### ISSUE THREAD

**Issue by JoyceYa** [umautobots/failing-to-learn#1]
Hi, I evaluated the given RRC detection results on kitti tracking dataset, and the F1 score I got was 0.6939, which is different from the F1 score (0.8395) you mentioned in the paper.

I found 15303 RRC detection results with confidence > 0.5, and 27057 ground truth Car (=Car+Van+Truck, height>=25px) labels in the kitti tracking dataset.  14698 predictions were TP in my evaluation results, which results in precision =0.9605, recall = 0.5432, so the F1 score was 0.6939.

I checked my code many times, and could not find a explanation for the difference.

Do you have any ideas? The F1 score I got was similar with the F1 score you gave in the paper for SSD model. Is it possible that the RRC results are actually SSD results? Or there are mistakes in my statistics?

Looking forward to your reply, thanks!

**Comment by JoyceYa** [comment]
> Hi, I evaluated the given RRC detection results on kitti tracking dataset, and the F1 score I got was 0.6939, which is different from the F1 score (0.8395) you mentioned in the paper.
> 
> I found 15303 RRC detection results with confidence > 0.5, and 27057 ground truth Car (=Car+Van+Truck) labels in the kitti tracking dataset. 14698 predictions were TP in my evaluation results, which results in precision =0.9605, recall = 0.5432, so the F1 score was 0.6939.
> 
> I checked my code many times, and could not find a explanation for my evaluation results.
> 
> Do you have any ideas? The F1 score I got was similar with the F1 score you gave in the paper for SSD model. Is it possible that the RRC results are actually SSD results? Or there are mistakes in my statistics?
> 
> Looking forward to your reply, thanks!

**Comment by srmanikandasriram** [comment]
Hi,

The evaluation was done using the KITTI evaluation kit which also places limits on max truncation and max occlusion levels. The numbers reported in the paper were for the moderate evaluation level, which is the default level used to rank entries in the KITTI benchmark. This was not explicitly mentioned in the paper. I have now added a note in the Readme of this repository to clarify the same. 

For the moderate evaluation level, the KITTI tracking dataset has 18580 ground truth labels. With a confidence threshold of 0.5, the RRC detector achieves 13366 True Positives, 285 False Positives and 4826 False Negatives. This gives an F1 score of 0.8395 as reported in the paper.
